### ISSUE TITLE
Recipes crash client joining server nullPointerException

### ISSUE THREAD

**Issue by hotdog95** [leoddd/anvilrecipes#1]
Forge Version 31.2.31

The client is unable to connect to a server with anvil smithing recipes, recipes function as expected on client host, but once a server is hosting, a client cannot join the server, is hit with a null pointer exception.

The recipe type used: anvilrecipes:additionsmithing

`
{
    "type": "anvilrecipes:additionsmithing",
    "input": {
      "xp": 0,
      "refineAll": false,
      "left": {
        "item": "minecraft:diamond_axe"
      },
      "right": {
        "item": "futureversions:netheriteingot",
        "keep": false
      }
    },
    "output": {
      "result": {
        "item": "futureversions:netheriteaxe"
      }
    }
  }
`

**Comment by timschellenberg** [comment]
I'll take a look at it later today or tomorrow, I had tested server functionality with a local server but I never tried to actually connect to it in the last stages of development, oops.

I'll let you know when it's been resolved.

**Comment by timschellenberg** [comment]
bfbd830
Fixed it, uploaded the update to Twitch: https://www.curseforge.com/minecraft/mc-mods/anvil-recipes/files/3015632
It might take a couple of hours for it to show up publically, it's under review for now.

![image](https://user-images.githubusercontent.com/20242421/88491004-c62fea00-cf9f-11ea-85a6-fe521003fc84.png)
